name: mentormeister
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  google_fonts: 6.1.0
  dotted_border: ^2.1.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
#  audioplayers: 5.2.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Login/
    - assets/teacher/
    - assets/students/
    - assets/subscription/
  

  
  

  
  

  
  
  
  
  

  fonts:
    - family: LiveSession
      fonts:
        - asset: assets/fonts/LiveSession.ttf

  
  
  
  
  
  
  
  
